/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateAccount.java
 *
 * Created on Mar 1, 2012, 10:36:53 PM
 */
package banksystem;

import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun Kodagoda
 */
public class CreateAccount extends javax.swing.JFrame {
    
    void clearTextFields(){
        txtAddress.setText("");
        txtDoB.setText("");
        txtFName.setText("");
        txtLName.setText("");
        txtPhone.setText("");
        txtNIC.setText("");
        txtAuthBy.setText("");
        txtCurODLimit.setText("");
        txtCur_ODIntRate.setText("");
        txtIntDeposit.setText("");
        txtIntroBy.setText("");
        txtPIN.setText("");
        txtAccNo.setText("");
        txtSavIntRate.setText("");
        txtSavMinBalance.setText("");
        txtDateOpened.setText("");
        lblMainDisplay.setText("");
        btnCreate.setEnabled(false);
        optCurr.setSelected(false);
        optSave.setSelected(false);
        chkActive.setSelected(false);
        buttonGroup1.clearSelection();
        
       
        pnlCurrent.setEnabled(false);
        pnlSavings.setEnabled(false);
        Component[] comp = pnlCurrent.getComponents();
        for (int i = 0; i < comp.length; i++)
        {
            comp[i].setEnabled(false);
        }
        
        Component[] comp2 = pnlSavings.getComponents();
        for (int i = 0; i < comp2.length; i++)
        {
            comp2[i].setEnabled(false);
            
        }
        
        txtFName.requestFocus();
        
    }
    
    
    
    String formType = null;
    /** Creates new form CreateAccount */
    public CreateAccount(String perantForm) {
        this.formType = perantForm;
        initComponents();
        pnlCurrent.setEnabled(false);
        pnlSavings.setEnabled(false);
        Component[] comp = pnlCurrent.getComponents();
        for (int i = 0; i < comp.length; i++)
        {
            comp[i].setEnabled(false);
        }
        
        Component[] comp2 = pnlSavings.getComponents();
        for (int i = 0; i < comp2.length; i++)
        {
            comp2[i].setEnabled(false);
            
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pnlCustomer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtDoB = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        pnlAccount = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        optSave = new javax.swing.JRadioButton();
        optCurr = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtIntDeposit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAuthBy = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDateOpened = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        pnlSavings = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtSavMinBalance = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSavIntRate = new javax.swing.JTextField();
        pnlCurrent = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCurODLimit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCur_ODIntRate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtIntroBy = new javax.swing.JTextField();
        pnlValidation = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnValidate = new javax.swing.JButton();
        txtAccNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPIN = new javax.swing.JTextField();
        lblMainDisplay = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Account");
        setBounds(new java.awt.Rectangle(141, 25, 0, 0));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/CreateAcount.png"))); // NOI18N

        pnlCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        pnlCustomer.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel5.setText("Phone No.");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel6.setText("Date Of Birth");

        txtFName.setFont(new java.awt.Font("Verdana", 0, 14));
        txtFName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        txtLName.setFont(new java.awt.Font("Verdana", 0, 14));
        txtLName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Verdana", 0, 14));
        txtAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtPhone.setFont(new java.awt.Font("Verdana", 0, 14));
        txtPhone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });

        txtDoB.setFont(new java.awt.Font("Verdana", 0, 14));
        txtDoB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoBActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel17.setText("NIC Number");

        txtNIC.setFont(new java.awt.Font("Verdana", 0, 14));
        txtNIC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        txtNIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNICFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlCustomerLayout = new javax.swing.GroupLayout(pnlCustomer);
        pnlCustomer.setLayout(pnlCustomerLayout);
        pnlCustomerLayout.setHorizontalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(56, 56, 56)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFName, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(txtLName, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCustomerLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCustomerLayout.createSequentialGroup()
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        pnlCustomerLayout.setVerticalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerLayout.createSequentialGroup()
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCustomerLayout.createSequentialGroup()
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel7.setText("Account Type");

        buttonGroup1.add(optSave);
        optSave.setFont(new java.awt.Font("Segoe UI Light", 1, 12));
        optSave.setText("Savings Account");
        optSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSaveActionPerformed(evt);
            }
        });

        buttonGroup1.add(optCurr);
        optCurr.setFont(new java.awt.Font("Segoe UI Light", 1, 12));
        optCurr.setText("Current Account");
        optCurr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCurrActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel8.setText("Initial Deposit (Rs.)");

        txtIntDeposit.setFont(new java.awt.Font("Verdana", 0, 14));
        txtIntDeposit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtIntDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntDepositActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel9.setText("Authorized By");

        txtAuthBy.setFont(new java.awt.Font("Verdana", 0, 14));
        txtAuthBy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtAuthBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthByActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel10.setText("Date Opened");

        txtDateOpened.setFont(new java.awt.Font("Verdana", 0, 14));
        txtDateOpened.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDateOpened.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOpenedActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel11.setText("Status : (Active)");

        pnlSavings.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Savings ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 12))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel12.setText("Interest Rate");

        txtSavMinBalance.setFont(new java.awt.Font("Verdana", 0, 14));
        txtSavMinBalance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtSavMinBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavMinBalanceActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel13.setText("Minimum Balance");

        txtSavIntRate.setFont(new java.awt.Font("Verdana", 0, 14));
        txtSavIntRate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtSavIntRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavIntRateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSavingsLayout = new javax.swing.GroupLayout(pnlSavings);
        pnlSavings.setLayout(pnlSavingsLayout);
        pnlSavingsLayout.setHorizontalGroup(
            pnlSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSavingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSavingsLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSavIntRate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSavingsLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(txtSavMinBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSavingsLayout.setVerticalGroup(
            pnlSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSavingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSavIntRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSavMinBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCurrent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 12))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel14.setText("OD Limit");

        txtCurODLimit.setFont(new java.awt.Font("Verdana", 0, 14));
        txtCurODLimit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCurODLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurODLimitActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel15.setText("OD Interest Rate");

        txtCur_ODIntRate.setFont(new java.awt.Font("Verdana", 0, 14));
        txtCur_ODIntRate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCur_ODIntRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCur_ODIntRateActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel16.setText("Introduced By");

        txtIntroBy.setFont(new java.awt.Font("Verdana", 0, 14));
        txtIntroBy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtIntroBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntroByActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCurrentLayout = new javax.swing.GroupLayout(pnlCurrent);
        pnlCurrent.setLayout(pnlCurrentLayout);
        pnlCurrentLayout.setHorizontalGroup(
            pnlCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCurrentLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCurODLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCurrentLayout.createSequentialGroup()
                        .addGroup(pnlCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIntroBy, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCur_ODIntRate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCurrentLayout.setVerticalGroup(
            pnlCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCurODLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCur_ODIntRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(11, 11, 11)
                .addGroup(pnlCurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntroBy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAccountLayout = new javax.swing.GroupLayout(pnlAccount);
        pnlAccount.setLayout(pnlAccountLayout);
        pnlAccountLayout.setHorizontalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optSave)
                    .addComponent(txtIntDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuthBy, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateOpened, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkActive)
                    .addComponent(optCurr))
                .addGap(111, 111, 111)
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSavings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlAccountLayout.setVerticalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountLayout.createSequentialGroup()
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccountLayout.createSequentialGroup()
                        .addComponent(pnlSavings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(optSave))
                        .addGap(10, 10, 10)
                        .addComponent(optCurr)
                        .addGap(18, 18, 18)
                        .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(pnlAccountLayout.createSequentialGroup()
                                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtIntDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtAuthBy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtDateOpened, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(chkActive, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlValidation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Validate Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel18.setText("Account No.");

        btnValidate.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnValidate.setText("Validate Input ");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });

        txtAccNo.setEditable(false);
        txtAccNo.setFont(new java.awt.Font("Verdana", 0, 18));
        txtAccNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel19.setText("PIN No.");

        txtPIN.setEditable(false);
        txtPIN.setFont(new java.awt.Font("Verdana", 0, 18));
        txtPIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPIN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblMainDisplay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18));
        lblMainDisplay.setForeground(new java.awt.Color(51, 153, 0));
        lblMainDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout pnlValidationLayout = new javax.swing.GroupLayout(pnlValidation);
        pnlValidation.setLayout(pnlValidationLayout);
        pnlValidationLayout.setHorizontalGroup(
            pnlValidationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValidationLayout.createSequentialGroup()
                .addGroup(pnlValidationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlValidationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlValidationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(pnlValidationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPIN, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtAccNo, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                    .addGroup(pnlValidationLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnValidate))
                    .addGroup(pnlValidationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMainDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlValidationLayout.setVerticalGroup(
            pnlValidationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValidationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlValidationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlValidationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMainDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCreate.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnCreate.setText("Create Account");
        btnCreate.setEnabled(false);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnClear.setText("Clear Fields");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreate)
                            .addComponent(btnClear)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit))
                    .addComponent(pnlValidation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnClear, btnCreate, btnExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlValidation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, btnClear, btnCreate, btnExit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        txtPhone.requestFocus();
    }//GEN-LAST:event_txtAddressActionPerformed

    private void optSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSaveActionPerformed
        pnlSavings.setEnabled(true);
        pnlCurrent.setEnabled(false);
        Component[] comp = pnlCurrent.getComponents();
        for (int i = 0; i < comp.length; i++)
        {
            comp[i].setEnabled(false);
        }
        
        Component[] comp2 = pnlSavings.getComponents();
        for (int i = 0; i < comp2.length; i++)
        {
            comp2[i].setEnabled(true);
        }
        
       
        
    }//GEN-LAST:event_optSaveActionPerformed

    private void optCurrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCurrActionPerformed
        pnlCurrent.setEnabled(true);
        pnlSavings.setEnabled(false);
        Component[] comp = pnlSavings.getComponents();
        for (int i = 0; i < comp.length; i++)
        {
            comp[i].setEnabled(false);
            
        }
        
        Component[] comp2 = pnlCurrent.getComponents();
        for (int i = 0; i < comp2.length; i++)
        {
            comp2[i].setEnabled(true);
        }
        
        
    }//GEN-LAST:event_optCurrActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (formType.equals("opr"))
        {
            this.dispose();
            new OperatorMainMenu().setVisible(true);
        }
        else if (formType.equals("admin"))
        {
            this.dispose();
            new AdminMainMenu().setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        txtLName.requestFocus();
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        txtAddress.requestFocus();
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        txtDoB.requestFocus();
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoBActionPerformed
        txtNIC.requestFocus();
    }//GEN-LAST:event_txtDoBActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        optSave.requestFocus();
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtIntDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntDepositActionPerformed
        txtAuthBy.requestFocus();
    }//GEN-LAST:event_txtIntDepositActionPerformed

    private void txtAuthByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthByActionPerformed
        txtDateOpened.requestFocus();
    }//GEN-LAST:event_txtAuthByActionPerformed

    private void txtDateOpenedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOpenedActionPerformed
        chkActive.requestFocus();
    }//GEN-LAST:event_txtDateOpenedActionPerformed

    private void txtSavIntRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavIntRateActionPerformed
        txtSavMinBalance.requestFocus();
    }//GEN-LAST:event_txtSavIntRateActionPerformed

    private void txtCurODLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurODLimitActionPerformed
        txtCur_ODIntRate.requestFocus();
    }//GEN-LAST:event_txtCurODLimitActionPerformed

    private void txtCur_ODIntRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCur_ODIntRateActionPerformed
        txtIntroBy.requestFocus();
    }//GEN-LAST:event_txtCur_ODIntRateActionPerformed

    private void txtSavMinBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavMinBalanceActionPerformed
        btnValidate.requestFocus();
    }//GEN-LAST:event_txtSavMinBalanceActionPerformed

    private void txtIntroByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntroByActionPerformed
        btnValidate.requestFocus();
    }//GEN-LAST:event_txtIntroByActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        Random rand = new Random();
        int i = rand.nextInt(90000) + 10000;
        String pinNo = String.valueOf(i);
        String accNum = "X";
        String tempAccNo = "1020001";
        long aNo;                
        
        if (optCurr.isSelected())
        {
            if (!(txtAddress.getText().equals("") ||
                txtAuthBy.getText().equals("") ||
                    txtCurODLimit.getText().equals("") ||
                    txtCur_ODIntRate.getText().equals("") ||
                    txtDateOpened.getText().equals("") ||
                    txtDoB.getText().equals("") ||
                    txtFName.getText().equals("") ||
                    txtIntDeposit.getText().equals("") ||
                    txtIntroBy.getText().equals("") ||
                    txtLName.getText().equals("") ||
                    txtNIC.getText().equals("") ||
                    txtPhone.getText().equals("")))
            {
                try {
                        Connection dbConnect = DBConnection.connect();
                        Statement dbQuary = dbConnect.createStatement();
                        ResultSet result = dbQuary.executeQuery("SELECT accNo FROM accounts;");

                        while(result.next())
                        {
                            accNum = result.getString("accNo");
                        }

                        if (accNum.equals("X"))
                        {
                            txtAccNo.setText(tempAccNo);
                        }
                        else
                        {
                            aNo = Long.parseLong(accNum);
                            aNo++;
                            accNum = String.valueOf(aNo);
                            txtAccNo.setText(accNum);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error accessing 'Accounts' table.\nError Message : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                //txtAccNo.setText(pinNo);
                txtPIN.setText(pinNo);
                lblMainDisplay.setText("Verification Complete");
                btnCreate.setEnabled(true);
            }
            else
            {
                lblMainDisplay.setText("Verification Failed");
                txtAccNo.setText("");
                txtPIN.setText("");
                btnCreate.setEnabled(false);
            }
        }
        else if (optSave.isSelected())
        {
            if(!(txtAddress.getText().equals("") ||
                txtAuthBy.getText().equals("") ||
                    txtSavIntRate.getText().equals("") ||
                    txtSavMinBalance.getText().equals("") ||
                    txtDateOpened.getText().equals("") ||
                    txtDoB.getText().equals("") ||
                    txtFName.getText().equals("") ||
                    txtIntDeposit.getText().equals("") ||
                    txtLName.getText().equals("") ||
                    txtNIC.getText().equals("") ||
                    txtPhone.getText().equals("")))
            {
                try {
                        Connection dbConnect = DBConnection.connect();
                        Statement dbQuary = dbConnect.createStatement();
                        ResultSet result = dbQuary.executeQuery("SELECT accNo FROM accounts;");

                        while(result.next())
                        {
                            accNum = result.getString("accNo");
                        }

                        if (accNum.equals("X"))
                        {
                            txtAccNo.setText(tempAccNo);
                        }
                        else
                        {
                            aNo = Long.parseLong(accNum);
                            aNo++;
                            accNum = String.valueOf(aNo);
                            txtAccNo.setText(accNum);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error accessing 'Accounts' table.\nError Message : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                //txtAccNo.setText(pinNo);
                txtPIN.setText(pinNo);
                lblMainDisplay.setText("Verification Complete");
                btnCreate.setEnabled(true);
                
            }
            else
            {
                lblMainDisplay.setText("Verification Failed");
                txtAccNo.setText("");
                txtPIN.setText("");
                btnCreate.setEnabled(false);
            }
        }
          
        
        
        
    }//GEN-LAST:event_btnValidateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String accType;
        String status;
        
        
        if(chkActive.isSelected())
            status = "Active";        
        else
            status = "Deactive";
           
        
        if (optCurr.isSelected())
        {
            accType = "cur";
            CurrentAccount newCurAcc = new CurrentAccount(txtAccNo.getText(), txtFName.getText() + " " + txtLName.getText(), status, txtAuthBy.getText(), "CURDATE()", "N/A", accType, Float.parseFloat(txtIntDeposit.getText()), Float.parseFloat(txtIntDeposit.getText()), Float.parseFloat(txtCurODLimit.getText()), Float.parseFloat(txtCur_ODIntRate.getText()), txtIntroBy.getText());
            Customer newCustomer = new Customer(txtFName.getText() + " " + txtLName.getText(), txtNIC.getText(), txtAddress.getText(), txtPhone.getText(), txtDoB.getText(), txtAccNo.getText(), txtPIN.getText());
            if (newCurAcc.create() && newCustomer.create())
            {
                JOptionPane.showMessageDialog(null, "Account created successfully.", "Create Account", JOptionPane.INFORMATION_MESSAGE);
                this.clearTextFields();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Account creation failed.", "Create Account", JOptionPane.ERROR_MESSAGE);
            }
                    
        }
        else if(optSave.isSelected())
        {
            accType = "sav";
            SavingsAccount newSavAcc = new SavingsAccount(txtAccNo.getText(), txtFName.getText() + " " + txtLName.getText(), status, txtAuthBy.getText(), "CURDATE()", "N/A", accType, Float.parseFloat(txtIntDeposit.getText()), Float.parseFloat(txtIntDeposit.getText()), Float.parseFloat(txtSavMinBalance.getText()), Float.parseFloat(txtSavIntRate.getText()));
            Customer newCustomer = new Customer(txtFName.getText() + " " + txtLName.getText(), txtNIC.getText(), txtAddress.getText(), txtPhone.getText(), txtDoB.getText(), txtAccNo.getText(), txtPIN.getText());
            
            if (newSavAcc.create() && newCustomer.create())
            {
                JOptionPane.showMessageDialog(null, "Account created successfully.", "Create Account", JOptionPane.INFORMATION_MESSAGE);
                this.clearTextFields();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Account creation failed.", "Create Account", JOptionPane.ERROR_MESSAGE);
            }
        }
            
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtNICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNICFocusLost
        String nicNum = txtNIC.getText();
        if (!nicNum.equals(""))
        {
            
            if (!(ValidateString.length(nicNum, 10) && ValidateString.charAt(nicNum, 9, 'V')))
            {
               JOptionPane.showMessageDialog(null, "Invalid NIC Number.\nLength or Format is Invalid", "Invalid NIC", JOptionPane.WARNING_MESSAGE);
                txtNIC.setText("");
                txtNIC.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNICFocusLost

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
        String phoneNum = txtPhone.getText();
        if (!phoneNum.equals(""))
        {
            if (!ValidateString.length(phoneNum, 10))
            {
                JOptionPane.showMessageDialog(null, "Invalid Phone Number.\nLength is Invalid", "Invalid Phone Number", JOptionPane.WARNING_MESSAGE);
                txtPhone.setText("");
                txtPhone.requestFocus();
            }
        }
    }//GEN-LAST:event_txtPhoneFocusLost

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.clearTextFields();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CreateAccount(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnValidate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMainDisplay;
    private javax.swing.JRadioButton optCurr;
    private javax.swing.JRadioButton optSave;
    private javax.swing.JPanel pnlAccount;
    private javax.swing.JPanel pnlCurrent;
    private javax.swing.JPanel pnlCustomer;
    private javax.swing.JPanel pnlSavings;
    private javax.swing.JPanel pnlValidation;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAuthBy;
    private javax.swing.JTextField txtCurODLimit;
    private javax.swing.JTextField txtCur_ODIntRate;
    private javax.swing.JTextField txtDateOpened;
    private javax.swing.JTextField txtDoB;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtIntDeposit;
    private javax.swing.JTextField txtIntroBy;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtPIN;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSavIntRate;
    private javax.swing.JTextField txtSavMinBalance;
    // End of variables declaration//GEN-END:variables
}
