/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmoloyeeSearch.java
 *
 * Created on Mar 3, 2012, 11:02:15 AM
 */
package banksystem;


import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun Kodagoda
 */
public class EmoloyeeSearch extends javax.swing.JFrame {

    /** Creates new form EmoloyeeSearch */
    public EmoloyeeSearch() {
        initComponents();
        try {
            Connection dbConnect = DBConnection.connect();
            Statement dbQuery = dbConnect.createStatement();                    
            ResultSet result = dbQuery.executeQuery("SELECT empNo FROM employee ORDER BY empNo;");
            Vector vec = new Vector();
            
            while(result.next()){
                String accountNumber = result.getString("empNo");
                vec.add(accountNumber);
            }
            
            lstEmpNo.setListData(vec);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error Accessing the database.\nError Message : " + e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    
    void clearTextFields() {
        txtAddress.setText("");
        txtDesig.setText("");
        txtEMPID.setText("");
        txtFulName.setText("");
        txtGrade.setText("");
        txtNIC.setText("");
        txtPhone.setText("");
        txtSearchEmp.setText("");
        txtdob.setText("");
        txtSearchEmp.requestFocus();
        lstEmpNo.clearSelection();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFulName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtEMPID = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtDesig = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchEmp = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmpNo = new javax.swing.JList();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCB_ChkBal1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Employees");
        setBounds(new java.awt.Rectangle(247, 115, 0, 0));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/SearchEmployees.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel3.setText("Full Name");

        txtFulName.setBackground(new java.awt.Color(204, 204, 204));
        txtFulName.setEditable(false);
        txtFulName.setFont(new java.awt.Font("Verdana", 1, 13));
        txtFulName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel4.setText("NIC No.");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel6.setText("Employee ID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel7.setText("Designation");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel8.setText("Pnone No.");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel9.setText("Grade");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel10.setText("Date Of Birth");

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtAddress.setEditable(false);
        txtAddress.setFont(new java.awt.Font("Verdana", 1, 13));
        txtAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtEMPID.setBackground(new java.awt.Color(204, 204, 204));
        txtEMPID.setEditable(false);
        txtEMPID.setFont(new java.awt.Font("Verdana", 1, 13));
        txtEMPID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtNIC.setBackground(new java.awt.Color(204, 204, 204));
        txtNIC.setEditable(false);
        txtNIC.setFont(new java.awt.Font("Verdana", 1, 13));
        txtNIC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtDesig.setBackground(new java.awt.Color(204, 204, 204));
        txtDesig.setEditable(false);
        txtDesig.setFont(new java.awt.Font("Verdana", 1, 13));
        txtDesig.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtGrade.setBackground(new java.awt.Color(204, 204, 204));
        txtGrade.setEditable(false);
        txtGrade.setFont(new java.awt.Font("Verdana", 1, 13));
        txtGrade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtPhone.setBackground(new java.awt.Color(204, 204, 204));
        txtPhone.setEditable(false);
        txtPhone.setFont(new java.awt.Font("Verdana", 1, 13));
        txtPhone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtdob.setBackground(new java.awt.Color(204, 204, 204));
        txtdob.setEditable(false);
        txtdob.setFont(new java.awt.Font("Verdana", 1, 13));
        txtdob.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFulName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEMPID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDesig, txtEMPID, txtGrade, txtNIC, txtPhone, txtdob});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFulName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEMPID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(362, 362, 362))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel2.setText("Employee ID");

        txtSearchEmp.setFont(new java.awt.Font("Verdana", 0, 14));
        txtSearchEmp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtSearchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchEmpActionPerformed(evt);
            }
        });
        txtSearchEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchEmpFocusLost(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtSearchEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        lstEmpNo.setFont(new java.awt.Font("Tahoma", 0, 14));
        lstEmpNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEmpNoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstEmpNo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnCB_ChkBal1.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnCB_ChkBal1.setText("Clear");
        btnCB_ChkBal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCB_ChkBal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCB_ChkBal1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel1)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnCB_ChkBal1, btnExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCB_ChkBal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new AdminMainMenu().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void lstEmpNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEmpNoMouseClicked
        String listSel = lstEmpNo.getSelectedValue().toString();
        String temp = null;
        
        try {
            Connection dbConnect = DBConnection.connect();
            Statement dbQuery = dbConnect.createStatement();
            ResultSet result = dbQuery.executeQuery("SELECT * FROM employee WHERE empNo ='"+listSel+"';");
           
            while(result.next())
            {
                temp = result.getString("address");                
                txtAddress.setText(temp);
                
                temp = result.getString("designation");
                txtDesig.setText(temp);
                
                temp = result.getString("empNo");
                txtEMPID.setText(temp);
                
                temp=result.getString("name");
                txtFulName.setText(temp);
                
                temp = result.getString("grade");
                txtGrade.setText(temp);
                
                temp = result.getString("empNIC");
                txtNIC.setText(temp);
                
                temp = result.getString("phone");
                txtPhone.setText(temp);
                
                temp = result.getString("empNo");
                txtSearchEmp.setText(temp);
                
                temp = result.getString("dob");
                txtdob.setText(temp);
                               
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error accessing 'Employee Databases'.\nError Message : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {
        String accNO = txtSearchEmp.getText();
        if (!accNO.equals(""))
        {
            
            if (!(ValidateString.length(accNO, 7)))
            {
                
                JOptionPane.showMessageDialog(null, "Invalid Account Number\nError in Length of Account Number", "Account Number", JOptionPane.WARNING_MESSAGE);
                txtSearchEmp.setText("");
                txtSearchEmp.requestFocus();
            }
        }
    }//GEN-LAST:event_lstEmpNoMouseClicked

    private void btnCB_ChkBal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCB_ChkBal1ActionPerformed
        this.clearTextFields();
    }//GEN-LAST:event_btnCB_ChkBal1ActionPerformed

    private void txtSearchEmpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchEmpFocusLost
        String accNO = txtSearchEmp.getText();
        if (!accNO.equals(""))
        {
            
            if (!(ValidateString.length(accNO, 6) && ValidateString.charAt(accNO, 0, 'E') && ValidateString.charAt(accNO, 1, 'M') && ValidateString.charAt(accNO, 2, 'P')))
            {
                
                JOptionPane.showMessageDialog(null, "Invalid Employee Number\nError in Length  of Format for Employee Number", "Employee Number", JOptionPane.WARNING_MESSAGE);
                txtSearchEmp.setText("");
                txtSearchEmp.requestFocus();
            }
        }
    }//GEN-LAST:event_txtSearchEmpFocusLost

    private void txtSearchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchEmpActionPerformed
        btnSearch.requestFocus();
    }//GEN-LAST:event_txtSearchEmpActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String temp = null;
        String empNumber = txtSearchEmp.getText();
        
        try {
            Connection dbConnect = DBConnection.connect();
            Statement dbQuery = dbConnect.createStatement();
            ResultSet result = dbQuery.executeQuery("SELECT * FROM employee WHERE empNo ='"+empNumber+"';");
            
            if (result.next())
            {
                result.beforeFirst();
                while(result.next())
                {
                        temp = result.getString("address");                
                        txtAddress.setText(temp);
                
                        temp = result.getString("designation");
                        txtDesig.setText(temp);
                
                        temp = result.getString("empNo");
                        txtEMPID.setText(temp);
                        lstEmpNo.setSelectedValue(temp, true);
                
                        temp=result.getString("name");
                        txtFulName.setText(temp);
                
                        temp = result.getString("grade");
                        txtGrade.setText(temp);
                
                        temp = result.getString("empNIC");
                        txtNIC.setText(temp);
                
                        temp = result.getString("phone");
                        txtPhone.setText(temp);
                
                        temp = result.getString("dob");
                        txtdob.setText(temp);
                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Employee not found in the database.", "Search Employee", JOptionPane.INFORMATION_MESSAGE);
                this.clearTextFields();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error accessing 'Employee Databases'.\nError Message : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EmoloyeeSearch().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCB_ChkBal1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstEmpNo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDesig;
    private javax.swing.JTextField txtEMPID;
    private javax.swing.JTextField txtFulName;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearchEmp;
    private javax.swing.JTextField txtdob;
    // End of variables declaration//GEN-END:variables
}
