/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RemoveEmployee.java
 *
 * Created on Mar 3, 2012, 1:16:07 PM
 */
package banksystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun Kodagoda
 */
public class RemoveEmployee extends javax.swing.JFrame {

    /** Creates new form RemoveEmployee */
    public RemoveEmployee() {
        initComponents();
    }
    
    void clearTextFields(){
        txtAddresss.setText("");
        txtDesig.setText("");
        txtEmp.setText("");
        txtEmpID.setText("");
        txtEmpName.setText("");
        txtGrade.setText("");
        txtNIC.setText("");
        txtEmp.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmp = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        optName = new javax.swing.JRadioButton();
        optID = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAddresss = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        txtEmpID = new javax.swing.JTextField();
        txtDesig = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove Employee");
        setBounds(new java.awt.Rectangle(383, 75, 0, 0));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/RemoveEmployee.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel2.setText("Search By ");

        txtEmp.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEmp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtEmp.setEnabled(false);
        txtEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpActionPerformed(evt);
            }
        });
        txtEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmpFocusLost(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        buttonGroup1.add(optName);
        optName.setFont(new java.awt.Font("Segoe UI", 0, 12));
        optName.setText("Employee Name");
        optName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(optID);
        optID.setFont(new java.awt.Font("Segoe UI", 0, 12));
        optID.setText("Employee ID");
        optID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(optID)
                    .addComponent(optName))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(optName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel3.setText("Name");

        txtEmpName.setBackground(new java.awt.Color(204, 204, 204));
        txtEmpName.setEditable(false);
        txtEmpName.setFont(new java.awt.Font("Verdana", 1, 13));
        txtEmpName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel4.setText("NIC No.");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel5.setText("Address");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel8.setText("Designation");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel9.setText("Employee No.");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel11.setText("Grade");

        txtAddresss.setBackground(new java.awt.Color(204, 204, 204));
        txtAddresss.setEditable(false);
        txtAddresss.setFont(new java.awt.Font("Verdana", 1, 13));
        txtAddresss.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtNIC.setBackground(new java.awt.Color(204, 204, 204));
        txtNIC.setEditable(false);
        txtNIC.setFont(new java.awt.Font("Verdana", 1, 13));
        txtNIC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtGrade.setBackground(new java.awt.Color(204, 204, 204));
        txtGrade.setEditable(false);
        txtGrade.setFont(new java.awt.Font("Verdana", 1, 13));
        txtGrade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtEmpID.setBackground(new java.awt.Color(204, 204, 204));
        txtEmpID.setEditable(false);
        txtEmpID.setFont(new java.awt.Font("Verdana", 1, 13));
        txtEmpID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtDesig.setBackground(new java.awt.Color(204, 204, 204));
        txtDesig.setEditable(false);
        txtDesig.setFont(new java.awt.Font("Verdana", 1, 13));
        txtDesig.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpName, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(txtAddresss, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDesig, txtEmpID, txtGrade, txtNIC});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddresss, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(438, 438, 438))
        );

        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnRemove.setText("Remove");
        btnRemove.setEnabled(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel1)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new AdminMainMenu().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String emp = txtEmp.getText();
        String temp = null;
        String empID = null;
        Employee newEmp = new Employee();
        
        if (optID.isSelected())
        {
            try {
                Connection dbConnect = DBConnection.connect();
                Statement dbQuery = dbConnect.createStatement();
                ResultSet result = dbQuery.executeQuery("SELECT * FROM employee WHERE empNo = '"+emp+"';");
                
                if (!result.next())
                {
                    JOptionPane.showMessageDialog(null, "The Employee is not in the database.", "Employee Not Found", JOptionPane.INFORMATION_MESSAGE);
                    txtEmp.setText("");
                    btnRemove.setEnabled(false);
                    
                }
                else
                {
                    result.beforeFirst();
                    while(result.next())
                    {
                    
                        temp = result.getString("address");
                        txtAddresss.setText(temp);
                    
                        temp = result.getString("designation");
                        txtDesig.setText(temp);
                    
                        empID = result.getString("empNo");
                        txtEmpID.setText(empID);
                    
                        temp = result.getString("name");
                        txtEmpName.setText(temp);
                    
                        temp = result.getString("grade");
                        txtGrade.setText(temp);
                    
                        temp = result.getString("empNIC");
                        txtNIC.setText(temp);
                                        
                    }
                    btnRemove.setEnabled(true);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error accessing 'Employee Databases'.\nError Message : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        else if (optName.isSelected())
        {
            
            try {
                Connection dbConnect = DBConnection.connect();
                Statement dbQuery = dbConnect.createStatement();
                ResultSet result = dbQuery.executeQuery("SELECT * FROM employee WHERE name = '"+emp+"';");
                
                if (!result.next())
                {
                     JOptionPane.showMessageDialog(null, "The Employee is not in the database.", "Employee Not Found", JOptionPane.INFORMATION_MESSAGE);
                     txtEmp.setText("");
                     btnRemove.setEnabled(false);
                }
                else
                {   
                    result.beforeFirst();
                    while(result.next())
                    {
                    
                        temp = result.getString("address");
                        txtAddresss.setText(temp);
                    
                        temp = result.getString("designation");
                        txtDesig.setText(temp);
                    
                        temp = result.getString("empNo");
                        txtEmpID.setText(temp);
                    
                        temp = result.getString("name");
                        txtEmpName.setText(temp);
                    
                        temp = result.getString("grade");
                        txtGrade.setText(temp);
                    
                        temp = result.getString("empNIC");
                        txtNIC.setText(temp);
                    }                    
                    btnRemove.setEnabled(true);
                }
                   
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error accessing 'Employee Databases'.\nError Message : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        /*else 
        {
            JOptionPane.showMessageDialog(null, "The Employee is not in the database.", "Employee Not Found", JOptionPane.INFORMATION_MESSAGE);
            txtEmp.setText("");
            
        } */      
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void optNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optNameActionPerformed
        txtEmp.setEnabled(true);
        this.clearTextFields();
        
    }//GEN-LAST:event_optNameActionPerformed

    private void optIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optIDActionPerformed
        txtEmp.setEnabled(true);
        this.clearTextFields();
    }//GEN-LAST:event_optIDActionPerformed

    private void txtEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpActionPerformed
        btnSearch.requestFocus();
    }//GEN-LAST:event_txtEmpActionPerformed

    private void txtEmpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmpFocusLost
        String accNO = txtEmp.getText();
        if (optID.isSelected())
        {         
        
            if (!accNO.equals(""))
            {
                
               if (!(ValidateString.length(accNO, 6) && ValidateString.charAt(accNO, 0, 'E') && ValidateString.charAt(accNO, 1, 'M') && ValidateString.charAt(accNO, 2, 'P')))
               {
                
                   JOptionPane.showMessageDialog(null, "Invalid Employee Number\nError in Length  of Format for Employee Number", "Employee Number", JOptionPane.WARNING_MESSAGE);
                    txtEmp.setText("");
                  txtEmp.requestFocus();
               }
            }
        }
    }//GEN-LAST:event_txtEmpFocusLost

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String empNumber = txtEmpID.getText();
        Employee newEmp = new Employee();
        
        if (JOptionPane.showConfirmDialog(null, "This will permanently remove this employee from the database.\nAre you sure, do you want to continue?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
        {
            if (newEmp.remove(empNumber))
            {
                JOptionPane.showMessageDialog(null, "Employee removed from the database successfully", "Remove Employee", JOptionPane.INFORMATION_MESSAGE);
                this.clearTextFields();
                btnRemove.setEnabled(false);
               
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Failed to remove the employee", "Remove Employee", JOptionPane.ERROR_MESSAGE);
                this.clearTextFields();
                btnRemove.setEnabled(false);
            }
        }
        else
        {
            this.clearTextFields();
            btnRemove.setEnabled(false);
        }
        
                
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RemoveEmployee().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton optID;
    private javax.swing.JRadioButton optName;
    private javax.swing.JTextField txtAddresss;
    private javax.swing.JTextField txtDesig;
    private javax.swing.JTextField txtEmp;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtNIC;
    // End of variables declaration//GEN-END:variables
}
