/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateCustomerDetails.java
 *
 * Created on Mar 13, 2012, 9:12:09 AM
 */
package banksystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun Kodagoda
 */
public class UpdateCustomerDetails extends javax.swing.JFrame {

    /** Creates new form UpdateCustomerDetails */
    public UpdateCustomerDetails() {
        initComponents();
        btnOkAddress.setVisible(false);
        btnOkDob.setVisible(false);
        btnOkNIC.setVisible(false);
        btnOkName.setVisible(false);
        btnOkPhone.setVisible(false);
        txtAccNo.requestDefaultFocus();
        
    }
    
    void clearTextFields(){
        txtAccNo.setText("");
        txtAddress.setText("");
        txtDob.setText("");
        txtNIC.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtAccNo.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnEditName = new javax.swing.JButton();
        btnEditAddress = new javax.swing.JButton();
        btnEditNIC = new javax.swing.JButton();
        btnEditDob = new javax.swing.JButton();
        btnEditPhone = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnOkName = new javax.swing.JButton();
        btnOkAddress = new javax.swing.JButton();
        btnOkNIC = new javax.swing.JButton();
        btnOkDob = new javax.swing.JButton();
        btnOkPhone = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Customer Details");
        setBounds(new java.awt.Rectangle(360, 81, 0, 0));
        setResizable(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel2.setText("Enter Account Number");

        txtAccNo.setFont(new java.awt.Font("Verdana", 0, 16));
        txtAccNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccNoActionPerformed(evt);
            }
        });
        txtAccNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAccNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAccNoFocusLost(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnSearch.setText("Search Account");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSearch)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel5.setText("NIC Number");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel6.setText("Date Of Birth");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel7.setText("Phone No.");

        txtName.setBackground(new java.awt.Color(204, 204, 204));
        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Verdana", 1, 16));
        txtName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        txtNIC.setBackground(new java.awt.Color(204, 204, 204));
        txtNIC.setEditable(false);
        txtNIC.setFont(new java.awt.Font("Verdana", 1, 16));
        txtNIC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        txtNIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNICFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNICFocusLost(evt);
            }
        });

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtAddress.setEditable(false);
        txtAddress.setFont(new java.awt.Font("Verdana", 1, 16));
        txtAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });

        txtDob.setBackground(new java.awt.Color(204, 204, 204));
        txtDob.setEditable(false);
        txtDob.setFont(new java.awt.Font("Verdana", 1, 16));
        txtDob.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        txtDob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDobFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDobFocusLost(evt);
            }
        });

        txtPhone.setBackground(new java.awt.Color(204, 204, 204));
        txtPhone.setEditable(false);
        txtPhone.setFont(new java.awt.Font("Verdana", 1, 16));
        txtPhone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });

        btnEditName.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnEditName.setText("Edit");
        btnEditName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNameActionPerformed(evt);
            }
        });

        btnEditAddress.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnEditAddress.setText("Edit");
        btnEditAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAddressActionPerformed(evt);
            }
        });

        btnEditNIC.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnEditNIC.setText("Edit");
        btnEditNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNICActionPerformed(evt);
            }
        });

        btnEditDob.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnEditDob.setText("Edit");
        btnEditDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDobActionPerformed(evt);
            }
        });

        btnEditPhone.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnEditPhone.setText("Edit");
        btnEditPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPhoneActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnOkName.setFont(new java.awt.Font("Segoe UI", 1, 18));
        btnOkName.setForeground(new java.awt.Color(0, 153, 0));
        btnOkName.setText("√");

        btnOkAddress.setFont(new java.awt.Font("Segoe UI", 1, 18));
        btnOkAddress.setForeground(new java.awt.Color(0, 153, 0));
        btnOkAddress.setText("√");

        btnOkNIC.setFont(new java.awt.Font("Segoe UI", 1, 18));
        btnOkNIC.setForeground(new java.awt.Color(0, 153, 0));
        btnOkNIC.setText("√");

        btnOkDob.setFont(new java.awt.Font("Segoe UI", 1, 18));
        btnOkDob.setForeground(new java.awt.Color(0, 153, 0));
        btnOkDob.setText("√");

        btnOkPhone.setFont(new java.awt.Font("Segoe UI", 1, 18));
        btnOkPhone.setForeground(new java.awt.Color(0, 153, 0));
        btnOkPhone.setText("√");

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOkPhone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditDob)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOkDob)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditNIC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOkNIC)
                        .addGap(45, 45, 45))
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(txtAddress))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOkName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOkAddress))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditName)
                            .addComponent(btnOkName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditAddress)
                            .addComponent(btnOkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditNIC)
                                    .addComponent(btnOkNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditDob)
                                    .addComponent(btnOkDob, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEditPhone)
                                    .addComponent(btnOkPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditPhone, btnOkPhone, txtPhone});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditDob, btnOkDob, txtDob});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditNIC, btnOkNIC, txtNIC});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditAddress, btnOkAddress, txtAddress});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditName, btnOkName, txtName});

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/UpdateCustomerDetails2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addGap(24, 24, 24))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, btnExit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccNoActionPerformed
        btnSearch.requestFocus();
}//GEN-LAST:event_txtAccNoActionPerformed

    private void txtAccNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAccNoFocusGained
        //this.clearTextFields();
}//GEN-LAST:event_txtAccNoFocusGained

    private void txtAccNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAccNoFocusLost
        String accNO = txtAccNo.getText();
        /*if (!accNO.equals("")) {
            
            if (!(ValidateString.length(accNO, 7))) {
                
                JOptionPane.showMessageDialog(null, "Invalid Account Number\nError in Length of Account Number", "Account Number", JOptionPane.WARNING_MESSAGE);
                txtCB_AccNo.setText("");
                txtCB_AccNo.requestFocus();
            }
        }*/
}//GEN-LAST:event_txtAccNoFocusLost

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String accountNumber;
        String name = "";
        String adr = "";
        String nic = "";
        String dob = "";
        String phone = "";
        String AccNo = "";
        
        if (txtAccNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter an Account Number!.", "Account Number", JOptionPane.WARNING_MESSAGE);
            txtAccNo.requestFocus();
        }
        else
        {
            accountNumber = txtAccNo.getText();
            try {                
                Connection dbConnect = DBConnection.connect();
                Statement dbQuery = dbConnect.createStatement();
                ResultSet result = dbQuery.executeQuery("SELECT * FROM customer WHERE accNo = '"+accountNumber+"';");
                
                while(result.next())
                {
                    AccNo = result.getString("accNo");
                    name = result.getString("name");
                    adr = result.getString("address");
                    nic = result.getString("cusNIC");
                    dob = result.getString("dob");
                    phone = result.getString("phone");
                }
                
                if (AccNo.equals(accountNumber))
                {
                    txtAddress.setText(adr);
                    txtDob.setText(dob);
                    txtNIC.setText(nic);
                    txtName.setText(name);
                    txtPhone.setText(phone);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Account not found in the Database", "Account Not Found", WIDTH);
                    this.clearTextFields();
                } 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error Reading from the 'Customer Database'\nError Message : " + e.getMessage(), "Database Access Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_btnSearchActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        btnOkName.setVisible(false);
        txtName.setEditable(false);
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        btnOkName.setVisible(false);
        txtName.setEditable(false);
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        btnOkNIC.setVisible(false);
        txtNIC.setEditable(false);
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtNICFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNICFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICFocusGained

    private void txtNICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNICFocusLost
        btnOkNIC.setVisible(false);
        txtNIC.setEditable(false);
    }//GEN-LAST:event_txtNICFocusLost

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        btnOkAddress.setVisible(false);
        txtAddress.setEditable(false);
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        btnOkAddress.setVisible(false);
        txtAddress.setEditable(false);
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        btnOkDob.setVisible(false);
        txtDob.setEditable(false);
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtDobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDobFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobFocusGained

    private void txtDobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDobFocusLost
        btnOkDob.setVisible(false);
        txtDob.setEditable(false);
    }//GEN-LAST:event_txtDobFocusLost

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        btnOkPhone.setVisible(false);
        txtPhone.setEditable(false);
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
        btnOkPhone.setVisible(false);
        txtPhone.setEditable(false);
    }//GEN-LAST:event_txtPhoneFocusLost

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new OperatorMainMenu().setVisible(true);
}//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
}//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Connection dbConnect = DBConnection.connect();
            PreparedStatement dbUpdate = dbConnect.prepareStatement("UPDATE customer SET cusNIC = '"+txtNIC.getText()+"', name = '"+txtName.getText()+"', address = '"+txtAddress.getText()+"', phone = '"+txtPhone.getText()+"', dob = '"+txtDob.getText()+"' WHERE accNo = '"+txtAccNo.getText()+"';");
            dbUpdate.executeUpdate();
            dbUpdate.close();
            
            dbUpdate = dbConnect.prepareStatement("UPDATE accounts SET name = '"+txtName.getText()+"' WHERE accNo = '"+txtAccNo.getText()+"';");
            dbUpdate.executeUpdate();
            dbUpdate.close();
            
            JOptionPane.showMessageDialog(null, "Customer Details update Completed.", "Database Update", JOptionPane.INFORMATION_MESSAGE);
            this.clearTextFields();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Updateing Database.\nError Message : " + e.getMessage(), "Database Update Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNameActionPerformed
        txtName.setEditable(true);
        btnOkName.setVisible(true);
        txtName.requestFocus();
    }//GEN-LAST:event_btnEditNameActionPerformed

    private void btnEditAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAddressActionPerformed
        txtAddress.setEditable(true);
        btnOkAddress.setVisible(true);
        txtAddress.requestFocus();
    }//GEN-LAST:event_btnEditAddressActionPerformed

    private void btnEditNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNICActionPerformed
        txtNIC.setEditable(true);
        btnOkNIC.setVisible(true);
        txtNIC.requestFocus();
    }//GEN-LAST:event_btnEditNICActionPerformed

    private void btnEditDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDobActionPerformed
        txtDob.setEditable(true);
        btnOkDob.setVisible(true);
        txtDob.requestFocus();
    }//GEN-LAST:event_btnEditDobActionPerformed

    private void btnEditPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPhoneActionPerformed
        txtPhone.setEditable(true);
        btnOkPhone.setVisible(true);
        txtPhone.requestFocus();
    }//GEN-LAST:event_btnEditPhoneActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.clearTextFields();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UpdateCustomerDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEditAddress;
    private javax.swing.JButton btnEditDob;
    private javax.swing.JButton btnEditNIC;
    private javax.swing.JButton btnEditName;
    private javax.swing.JButton btnEditPhone;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOkAddress;
    private javax.swing.JButton btnOkDob;
    private javax.swing.JButton btnOkNIC;
    private javax.swing.JButton btnOkName;
    private javax.swing.JButton btnOkPhone;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
