/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateAccount.java
 *
 * Created on Mar 3, 2012, 3:05:54 PM
 */
package banksystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Kasun Kodagoda
 */
public class UpdateAccount extends javax.swing.JFrame {
    String formType = null;
    float accountBalance = 0;
    float newAccountBalance = 0;

    /** Creates new form UpdateAccount */
    public UpdateAccount(String perantForm) {
        this.formType = perantForm;
        initComponents();
    }
    
    void clearTextFields(){
        txtAccBal.setText("");
        txtAccType.setText("");
        txtIntRate.setText("");
        txtNewBal.setText("");
        lblDisplay.setText("");
        txtUpdateAccNo.setText("");
        btnUpdate.setEnabled(false);
        txtUpdateAccNo.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUpdateAccNo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAccBal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtIntRate = new javax.swing.JTextField();
        txtAccType = new javax.swing.JTextField();
        lblDisplay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNewBal = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Account");
        setBounds(new java.awt.Rectangle(376, 30, 0, 0));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/UpdateAccount.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel2.setText("Account Number");

        txtUpdateAccNo.setFont(new java.awt.Font("Verdana", 0, 16));
        txtUpdateAccNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtUpdateAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateAccNoActionPerformed(evt);
            }
        });
        txtUpdateAccNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUpdateAccNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUpdateAccNoFocusLost(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtUpdateAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUpdateAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel3.setText("Account Balance");

        txtAccBal.setEditable(false);
        txtAccBal.setFont(new java.awt.Font("Verdana", 1, 16));
        txtAccBal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel4.setText("Interest Rate");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel5.setText("Account Type");

        txtIntRate.setEditable(false);
        txtIntRate.setFont(new java.awt.Font("Verdana", 1, 16));
        txtIntRate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtAccType.setEditable(false);
        txtAccType.setFont(new java.awt.Font("Verdana", 1, 16));
        txtAccType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblDisplay.setBackground(new java.awt.Color(102, 102, 102));
        lblDisplay.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblDisplay.setForeground(new java.awt.Color(0, 153, 0));
        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblDisplay.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18));
        jLabel7.setText("New Balance");

        txtNewBal.setBackground(new java.awt.Color(204, 204, 204));
        txtNewBal.setEditable(false);
        txtNewBal.setFont(new java.awt.Font("Consolas", 1, 24));
        txtNewBal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnUpdate.setText("Update Account");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtNewBal, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIntRate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNewBal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banksystem/Images/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel1)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (formType.equals("opr"))
        {
            this.dispose();
            new OperatorMainMenu().setVisible(true);
        }
        else if (formType.equals("admin"))
        {
            this.dispose();
            new AdminMainMenu().setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUpdateAccNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpdateAccNoFocusLost
        String accNO = txtUpdateAccNo.getText();
        if (!accNO.equals(""))
        {
            
            if (!(ValidateString.length(accNO, 7)))
            {
                
                JOptionPane.showMessageDialog(null, "Invalid Account Number\nError in Length of Account Number", "Account Number", JOptionPane.WARNING_MESSAGE);
                txtUpdateAccNo.setText("");
                txtUpdateAccNo.requestFocus();
            }
        }
    }//GEN-LAST:event_txtUpdateAccNoFocusLost

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String accNo = "";
        String accountNumber = "";
        String accountType = "";
        String accountStatus = "";
        
        
        float interest = 0;
        
        if ((accNo = txtUpdateAccNo.getText()).equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter an Account Number!", "Empty Field", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            try {
                Connection dbConnect = DBConnection.connect();
                Statement dbQuery = dbConnect.createStatement();
                ResultSet result = dbQuery.executeQuery("SELECT * FROM accounts WHERE accNo = '"+accNo+"';");
                
                while(result.next())
                {
                    accountNumber = result.getString("accNo");
                    accountType = result.getString("accType");
                    accountBalance = result.getFloat("balance");
                    accountStatus = result.getString("accStatus");
                }
                if (accountStatus.equals("Deactive"))
                {
                    JOptionPane.showMessageDialog(null, "The Account is Closed/Deactivated.", "Closed Account", JOptionPane.INFORMATION_MESSAGE);
                    this.clearTextFields();
                }
                else
                {
                    if (accountNumber.equals(accNo))
                    {
                        txtAccBal.setText("Rs." + String.valueOf(accountBalance));
                        txtIntRate.setText(String.valueOf(evt));
                        if (accountType.equals("sav"))
                        {
                            try {
                                Statement dbQuery1 = dbConnect.createStatement();
                                ResultSet result1 = dbQuery1.executeQuery("SELECT intRate FROM savings WHERE accNo = '"+accNo+"';");

                                while(result1.next())
                                {
                                    interest = result1.getFloat("intRate");
                                }

                            }catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "Error Message : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                            }
                            txtAccType.setText("Savings Account");
                            txtIntRate.setText(String.valueOf(interest));
                            btnUpdate.setEnabled(true);
                            lblDisplay.setForeground(Color.GREEN);
                            lblDisplay.setText("Account Identified Successfully");

                        }
                        else if (accountType.equals("cur"))
                        {
                            try {
                                Statement dbQuery1 = dbConnect.createStatement();
                                ResultSet result1 = dbQuery1.executeQuery("SELECT odInt FROM current WHERE accNo = '"+accNo+"';");

                                while(result1.next())
                                {
                                    interest = result1.getFloat("odInt");
                                }

                            }catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "Error Message : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                            }
                            txtAccType.setText("Current Account");
                            txtIntRate.setText(String.valueOf(interest));
                            btnUpdate.setEnabled(true);
                            lblDisplay.setForeground(Color.GREEN);
                            lblDisplay.setText("Account Identified Successfully");

                        }
                    }
                    else
                    {
                        //JOptionPane.showMessageDialog(null, "Account Number doesn't match.\nAccount not in the Database.", "Account Not Found", JOptionPane.INFORMATION_MESSAGE);
                        lblDisplay.setForeground(Color.RED);
                        lblDisplay.setText("Account Not Found");
                        //this.clearTextFields();
                        txtUpdateAccNo.setText("");
                    }
                    
                }          
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error Reading From 'Account Database'.\nError Message : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtUpdateAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateAccNoActionPerformed
        btnSearch.requestFocus();
    }//GEN-LAST:event_txtUpdateAccNoActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String aType = txtAccType.getText();
        
        if (aType.equals("Savings Account"))
        {
            SavingsAccount newSA = new SavingsAccount();
            newAccountBalance = newSA.updateInterest(txtUpdateAccNo.getText(), accountBalance);
            txtNewBal.setText("Rs." + String.valueOf(newAccountBalance));
        }
        else if (aType.equals("Current Account"))
        {
            CurrentAccount newCA = new CurrentAccount();
            newAccountBalance = newCA.updateInterest(txtUpdateAccNo.getText(), accountBalance);
            if (newAccountBalance == accountBalance)
            {
                lblDisplay.setForeground(Color.YELLOW);
                lblDisplay.setText("Account Not Updated");
            }                
            txtNewBal.setText("Rs." + String.valueOf(newAccountBalance));
        }
            
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.clearTextFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtUpdateAccNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpdateAccNoFocusGained
        lblDisplay.setText("");
    }//GEN-LAST:event_txtUpdateAccNoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UpdateAccount(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JTextField txtAccBal;
    private javax.swing.JTextField txtAccType;
    private javax.swing.JTextField txtIntRate;
    private javax.swing.JTextField txtNewBal;
    private javax.swing.JTextField txtUpdateAccNo;
    // End of variables declaration//GEN-END:variables
}
